"""Initial tables

Revision ID: 8e7013df6866
Revises: 
Create Date: 2025-03-05 14:13:16.275055

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e7013df6866'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolios')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('username')

    op.drop_table('users')
    with op.batch_alter_table('cryptocurrencies', schema=None) as batch_op:
        batch_op.drop_index('symbol')

    op.drop_table('cryptocurrencies')
    op.drop_table('transactions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('crypto_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transaction_type', mysql.ENUM('buy', 'sell'), nullable=False),
    sa.Column('price', mysql.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('quantity', mysql.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['crypto_id'], ['cryptocurrencies.id'], name='transactions_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='transactions_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('cryptocurrencies',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('symbol', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('current_price', mysql.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('market_cap', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('cryptocurrencies', schema=None) as batch_op:
        batch_op.create_index('symbol', ['symbol'], unique=True)

    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=True)
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('portfolios',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('crypto_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', mysql.DECIMAL(precision=18, scale=8), nullable=True),
    sa.ForeignKeyConstraint(['crypto_id'], ['cryptocurrencies.id'], name='portfolios_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='portfolios_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
